artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/Thivagar1994/End_to_end_Ml_Project/raw/refs/heads/main/wine_zip.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/WineQT.csv
  STATUS_FILE: artifacts/data_validation/status.txt
  